### ISSUE TITLE
Do not parse charges on Record parser

### ISSUE THREAD

**Issue by NickSchimek** [CodeForPortland/recordexpungPDX#34]
## Context
The record parser extracts the cases from the search results page. It also extracts the charges associated to the case, but this is not necessary since the charges can be extracted from the case details page in more detail. 

### Tasks

- [ ] Update tests to check the parser skips the charge column.
- [ ] Remove the sections responsible for parsing the charge columns for each case.
- [ ] Ensure all existing functionality does not change.

**Comment by maxkwallace** [comment]
@nwalton125 Hey! This task hasn't been updated in a few months so I just wanted to check in and see how it's going. Are you still working on this task? If not, or if I don't hear back, I will open it up for someone else to work on.

**Comment by nwalton125** [comment]
Hello!

Sorry! I am not, best to open it up for someone else.

**Comment by maxkwallace** [comment]
@nwalton125 no worries! Thanks for the reply :)

**Comment by NickSchimek** [comment]
@maxkwallace I added a temporary fix to this in another commit. It still parses the charges, but it doesn't save the results. We could probably close this issue?
It's not so important, but what I would actually like to see done is a complete re-write or refactor of the record parser so that it is easier to understand. What do you think?

**Comment by maxkwallace** [comment]
@NickSchimek sounds good, I'll close the issue.

Regarding the refactor I'd have to read the parser code myself in order to comment. I trust your judgment. There are a lot of factors that go into deciding whether a refactor makes sense but IMO the main ones are (1) whether the code is functioning well now and (2) whether or not it will need to be edited many times in the future.

**Comment by NickSchimek** [comment]
@maxkwallace yeah, I completely agree. It most likely will not have to be edited in the future, and it currently works so.... It was just something that would be nice, but is not currently necessary.
